# Databricks notebook source
# MAGIC %md
# MAGIC # Web Scraping with BeautifulSoup

# COMMAND ----------

# MAGIC %pip install beautifulsoup4

# COMMAND ----------

# MAGIC %sql
# MAGIC --create catalog scrapping;
# MAGIC use catalog scrapping;
# MAGIC --create schema release;
# MAGIC use schema release;

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE or replace TABLE data (
# MAGIC     id BIGINT GENERATED BY DEFAULT AS IDENTITY,
# MAGIC     title STRING,
# MAGIC     description STRING,
# MAGIC     links ARRAY<STRING>,
# MAGIC     month STRING,
# MAGIC     year STRING,
# MAGIC     category STRING,
# MAGIC     status String
# MAGIC ) USING DELTA

# COMMAND ----------

# MAGIC %sql
# MAGIC ALTER TABLE data SET TBLPROPERTIES (delta.enableChangeDataFeed = true);

# COMMAND ----------

import requests
from bs4 import BeautifulSoup
from urllib.parse import urljoin

# Define the base URL
base_url = 'https://docs.databricks.com/en/release-notes/product/'

# List of months and years
months = ['january', 'february', 'march', 'april', 'may', 'june', 'july', 'august', 'september', 'october', 'november', 'december']
years = ['2023', '2024']

results = []
# Initialize a list to store extracted data

# Iterate through each year and month
for year in years:
    for month in months:
        url = f'{base_url}{year}/{month}.html'
        response = requests.get(url)
        if response.status_code == 200:
            # Get the content of the response
            page_content = response.content
            # Step 1: Send an HTTP request to the webpage

            # Step 2: Parse the HTML content using BeautifulSoup
            soup = BeautifulSoup(response.content, 'html.parser')

            # Step 3: Extract all the <div> sections in the article body
            sections = soup.find_all('div', class_='section')

            # Step 4: Loop through each section to extract the required elements
            for i, section in enumerate(sections):
                if i == 0:
                    continue  # Skip the first section

                h2 = section.find('h2')  # Extract the title
                p_tags = section.find_all('p')  # Extract all <p> tags

                if h2 and len(p_tags) > 1:
                    title = h2.get_text(strip=True)
                    info = p_tags[1].get_text(strip=True)  # Extract the second <p> tag's text

                    # Remove text after "See"
                    info = info.split('See')[0].strip()

                    # Extract text from <ul> elements with class 'simple'
                    ul_simple = section.find('ul', class_='simple')
                    if ul_simple:
                        ul_text = ' '.join(li.get_text(strip=True) for li in ul_simple.find_all('li'))
                        info += f" {ul_text}"

                    # Extract links in the "See" section (if present)
                    see_links = section.find_all('a')
                    links = []

                    if see_links:
                        for link in see_links:
                            href = link.get('href')
                            if href and '#' not in href:  # Filter out links with '#'
                                absolute_href = urljoin(url, href)  # Convert to absolute URL
                                link_text = link.get_text(strip=True)
                                links.append(f"{absolute_href}")

                    # Append the title, information, links, and month to the results list
                    results.append([title, info, links, month, year])

# Print the results
for result in results:
    print(f"Title: {result[0]}")
    print(f"Information: {result[1]}")
    for link in result[2]:
        print(link)
    print(f"Month: {result[3]}")
    print(f"Year: {result[4]}")
    print("\n" + "="*50 + "\n")

# COMMAND ----------

display(results)

# COMMAND ----------

from pyspark.sql.types import StructType, StringType, ArrayType

# Define the schema
schema = StructType() \
    .add("title", StringType()) \
    .add("description", StringType()) \
    .add("links", ArrayType(StringType())) \
    .add("month", StringType()) \
    .add("year", StringType())

# Create the DataFrame with the specified schema
df = spark.createDataFrame(results, schema)

# Display the DataFrame
display(df)

# Write the DataFrame as a Delta table
df.write.format("delta").mode("overwrite").option('mergeSchema', 'true').saveAsTable("datas")

# COMMAND ----------

# MAGIC %sql
# MAGIC -- Create a temporary view without the `id` column
# MAGIC CREATE OR REPLACE TEMPORARY VIEW temp AS
# MAGIC SELECT *, ai_classify(description, ARRAY('Governance', 'Data Engineering', 'Generative AI/ LLM', 'Machine Learning', 'Administration', 'Security', 'Data Sharing')) AS category, ai_classify(description, ARRAY('GA', 'Public Preview', 'Private Preview')) AS status, 'id' as id 
# MAGIC FROM datas;
# MAGIC
# MAGIC -- Create the final view by selecting all columns from the temporary view and adding the `id` column

# COMMAND ----------

# MAGIC %sql
# MAGIC MERGE INTO data AS target
# MAGIC USING temp AS source
# MAGIC ON target.id = source.id
# MAGIC WHEN NOT MATCHED THEN
# MAGIC   INSERT (title, description, links, month, year, category, status)
# MAGIC   VALUES (source.title, source.description, source.links, source.month, source.year, source.category, source.status);

# COMMAND ----------

# MAGIC %sql
# MAGIC select * from data

# COMMAND ----------

# MAGIC %pip install databricks-vectorsearch
# MAGIC

# COMMAND ----------

# MAGIC %pip install --upgrade --force-reinstall databricks-vectorsearch
# MAGIC %pip install openai
# MAGIC %pip install --upgrade --quiet  langchain-core databricks-vectorsearch langchain-openai tiktoken
# MAGIC %pip install langchain
# MAGIC dbutils.library.restartPython()

# COMMAND ----------


from databricks.vector_search.client import VectorSearchClient
from langchain_community.vectorstores import DatabricksVectorSearch

vsc = VectorSearchClient(disable_notice=True)

index = vsc.get_index(endpoint_name='youssef_scrapping',index_name=
'scrapping.release.data_release')



# COMMAND ----------

from langchain_community.chat_models.databricks import ChatDatabricks
from langchain_community.embeddings import DatabricksEmbeddings
from langchain_community.vectorstores import DatabricksVectorSearch

chat_model = ChatDatabricks(endpoint="databricks-meta-llama-3-70b-instruct")
embeddings = DatabricksEmbeddings(endpoint="databricks-bge-large-en")
chat = chat_model.invoke("")
response = chat.query(question)
print(response)

# COMMAND ----------

print(chat_model.invoke("What is databricks?").content)

# COMMAND ----------

# MAGIC %pip install -U -qqqq databricks-agents mlflow langchain langchain_core langchain_community

# COMMAND ----------

# MAGIC %sql
# MAGIC WITH extracted_data AS (
# MAGIC   SELECT ai_fix_grammar(
# MAGIC     'Show me the new features that was released starting from  2024'
# MAGIC   ) AS fixed
# MAGIC )
# MAGIC
# MAGIC SELECT ai_extract(extracted_data.fixed,
# MAGIC     array('text', 'month', 'year')) AS fixed_text, fixed_text.month,fixed_text.year
# MAGIC FROM extracted_data

# COMMAND ----------

import mlflow
from operator import itemgetter
from langchain_core.output_parsers import StrOutputParser
from langchain_community.chat_models import ChatDatabricks
from langchain_core.prompts import PromptTemplate

question = "What are the latest features related to security in august"
results = index.similarity_search(
    query_text=question,
    columns=["links", "description", "title", "category", "status", "year", "month"],
    num_results=1,
    filters={"month": ["august"],"year":"2024"})

columns = [col['name'] for col in results['manifest']['columns']]
data_array = results['result']['data_array']

parsed_data_list = [dict(zip(columns, data)) for data in data_array]

context = ""
for parsed_data in parsed_data_list:
    context += f"""{parsed_data['title']} in the category {parsed_data['category']} has been released in {parsed_data['month']} {parsed_data['year']} means that {parsed_data['description']} here are the useful links: {parsed_data['links']}.
    """

# Extract month and year from the results
month = parsed_data_list[0]['month']
year = parsed_data_list[0]['year']

prompt = PromptTemplate(
    template="You are a Chatbot that answers only questions about Data and AI. Respond with a reply to the user's question. Here is the context: {context}, User's question: {question} if you have more than an answer right them as a list and return to a new line and you have links add them.",
    input_variables=['context', 'question'],
    output_variables=[],
)

model = ChatDatabricks(
    endpoint="databricks-meta-llama-3-1-405b-instruct",
    extra_params={"temperature": 0.05, "max_tokens": 1000},
)

chain = (prompt | model | StrOutputParser())

chain.invoke({"context": context, "question": question})

# COMMAND ----------

import mlflow
from operator import itemgetter
from langchain_core.output_parsers import StrOutputParser
from langchain_community.chat_models import ChatDatabricks
from langchain_core.prompts import PromptTemplate

question = "What are the features linked to Unity Catalog"
results = index.similarity_search(
    query_text=question,
    columns=["links", "description", "title", "category", "status", "year", "month"],
    num_results=5,
    )

columns = [col['name'] for col in results['manifest']['columns']]
data_array = results['result']['data_array']

parsed_data_list = [dict(zip(columns, data)) for data in data_array]

context = ""
for parsed_data in parsed_data_list:
    context += f"""{parsed_data['title']} in the category {parsed_data['category']} has been released in {parsed_data['month']} {parsed_data['year']} means that {parsed_data['description']} here are the useful links: {parsed_data['links']}.
    """

# Extract month and year from the results
month = parsed_data_list[0]['month']
year = parsed_data_list[0]['year']

prompt = PromptTemplate(
    template="You are a Chatbot that answers only questions about Databricks. Respond with a reply to the user's question. Here is the context: {context}, User's question: {question} if you have more than an answer right them as a list and return to a new line and you have links add them, don't say here the answer to your question just answer it directly",
    input_variables=['context', 'question'],
    output_variables=[],
)

model = ChatDatabricks(
    endpoint="databricks-meta-llama-3-1-405b-instruct",
    extra_params={"temperature": 0.05, "max_tokens": 1000},
)

chain = (prompt | model | StrOutputParser())

chain.invoke({"context": context, "question": question})

# COMMAND ----------

# Databricks notebook source
# MAGIC %md-sandbox
# MAGIC # Composable AI systems: Building and AI Stylist Specialist selling our products
# MAGIC
# MAGIC ## What's a composable AI systems
# MAGIC
# MAGIC LLMs are great at answering generate questions. However, this alone isn't enough to provide value to your customers.
# MAGIC
# MAGIC To be able to provide valuable answer, extra information is requred, specific to the user (your customer contract ID, the last email they sent to your support, your most recent sales report etc.).
# MAGIC
# MAGIC Composable AI systems are designed to answer this challenge. They are more advanced AI deployments, composed of multiple entities (tools) specialized in different action (retrieving information or acting on external systems). <br/>
# MAGIC
# MAGIC A a high level, you build & present a set of custom functions to the AI. The LLM can then reason about it, deciding which tool should be called and information gathered to answer the customer need.
# MAGIC
# MAGIC ## Building Composable AI Systems with Databricks Mosaic AI agent framework
# MAGIC
# MAGIC
# MAGIC Databricks simplifies this by providing a builtin service to:
# MAGIC
# MAGIC - Create and store your functions (tools) leveraging UC
# MAGIC - Execute the functions in a safe way
# MAGIC - Reason about the tools you selected and chain them together to properly answer your question. 
# MAGIC
# MAGIC A a high level, here is the AI system we will implement in this demo:
# MAGIC
# MAGIC <img src="https://github.com/databricks-demos/dbdemos-resources/blob/main/images/product/llm-tools-functions/llm-tools-functions-flow.png?raw=true" width="900px">
# MAGIC
# MAGIC
# MAGIC <!-- Collect usage data (view). Remove it to disable collection or disable tracker during installation. View README for more details.  -->
# MAGIC <img width="1px" src="https://ppxrzfxige.execute-api.us-west-2.amazonaws.com/v1/analytics?category=data-science&notebook=00-AI-function-tools-introduction&demo_name=llm-tools-functions&event=VIEW">

# COMMAND ----------

# MAGIC %pip install -U databricks-sdk==0.23.0 langchain-community==0.2.10 langchain-openai==0.1.19 mlflow==2.14.3 faker
# MAGIC dbutils.library.restartPython()

# COMMAND ----------

# MAGIC %run ./_resources/00-init $reset_all=false

# COMMAND ----------

# MAGIC %md
# MAGIC ## Creating our tools: Using Unity Catalog Functions
# MAGIC
# MAGIC Let's start by defining the functions our LLM will be able to execute. These functions can contain any logic, from simple SQL to advanced python.

# COMMAND ----------

# MAGIC %md 
# MAGIC ### Computing Mathematics: converting inches to centimeters
# MAGIC
# MAGIC Our online shop is selling across all regions, and we know our customers often ask to convert cm to inches. However, plain LLMs are quite bad at executing math. To solve this, let's create a simple function doing the conversion.
# MAGIC
# MAGIC We'll save this function within Unity Catalog. You can open the explorer to review the functions created in this notebook.
# MAGIC
# MAGIC *Note: This is a very simple first example for this demo. We'll implement a broader math tool later on.*

# COMMAND ----------

# DBTITLE 1,Convert inch to cm
# MAGIC %sql
# MAGIC CREATE OR REPLACE FUNCTION convert_inch_to_cm(size_in_inch FLOAT)
# MAGIC RETURNS FLOAT
# MAGIC LANGUAGE SQL
# MAGIC COMMENT 'convert size from inch to cm'
# MAGIC RETURN size_in_inch * 2.54;
# MAGIC
# MAGIC -- let's test our function:
# MAGIC SELECT convert_inch_to_cm(10) as 10_inches_in_cm;

# COMMAND ----------

# MAGIC %md 
# MAGIC ### Executing a tool to fetch internal data: getting the latest customer orders
# MAGIC
# MAGIC We want our stylist assistant to be able to list all existing customer orders

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE OR REPLACE FUNCTION get_customer_orders ()
# MAGIC RETURNS TABLE(user_id STRING,
# MAGIC   id STRING,
# MAGIC   transaction_date STRING,
# MAGIC   item_count DOUBLE,
# MAGIC   amount DOUBLE,
# MAGIC   order_status STRING)
# MAGIC COMMENT 'Returns a list of customer orders for the given customer ID (expect a UUID)'
# MAGIC LANGUAGE SQL
# MAGIC     RETURN
# MAGIC     SELECT o.* from tools_orders o 
# MAGIC     inner join tools_customers c on c.id = o.user_id 
# MAGIC     where email=current_user() ORDER BY transaction_date desc;
# MAGIC
# MAGIC SELECT * FROM get_customer_orders();

# COMMAND ----------

# MAGIC %md 
# MAGIC ### Executing a Python function to fetch external dataset in realtime: getting the weather
# MAGIC
# MAGIC We want our stylist assistant to give us recommendations based on the weather. Let's add a tool to fetch the weather based on longitude/latitude, using Python to call an external Weather API.

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE OR REPLACE FUNCTION get_weather(latitude DOUBLE, longitude DOUBLE)
# MAGIC RETURNS STRUCT<temperature_in_celsius DOUBLE, rain_in_mm DOUBLE>
# MAGIC LANGUAGE PYTHON
# MAGIC COMMENT 'This function retrieves the current temperature and rain information for a given latitude and longitude using the Open-Meteo API.'
# MAGIC AS
# MAGIC $$
# MAGIC   try:
# MAGIC     import requests as r
# MAGIC     #Note: this is provided for education only, non commercial - please get a license for real usage: https://api.open-meteo.com. Let s comment it to avoid issues for now
# MAGIC     #weather = r.get(f'https://api.open-meteo.com/v1/forecast?latitude={latitude}&longitude={longitude}&current=temperature_2m,rain&forecast_days=1').json()
# MAGIC     return {
# MAGIC       "temperature_in_celsius": weather["current"]["temperature_2m"],
# MAGIC       "rain_in_mm": weather["current"]["rain"]
# MAGIC     }
# MAGIC   except:
# MAGIC     return {"temperature_in_celsius": 25.0, "rain_in_mm": 0.0}
# MAGIC $$;
# MAGIC
# MAGIC -- let's test our function:
# MAGIC SELECT get_weather(52.52, 13.41) as weather;

# COMMAND ----------

# MAGIC %md 
# MAGIC ### Creating a function calling an LLMs with specific prompt as a tool
# MAGIC
# MAGIC You can also register tools containing custom prompts that your LLM can use to to execute actions based on the customer context.
# MAGIC
# MAGIC Let's create a tool that recommend the style for our user, based on the current weather.

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE OR REPLACE FUNCTION recommend_outfit_description(requested_style STRING, temperature_in_celsius FLOAT, rain_in_mm FLOAT)
# MAGIC RETURNS STRING
# MAGIC LANGUAGE SQL
# MAGIC COMMENT 'This function generate a stylist outfit description based on initial request and the current weather.'
# MAGIC RETURN SELECT ai_query('databricks-meta-llama-3-70b-instruct',
# MAGIC     CONCAT("You are a stylist assistant. Your goal is to give recommendation on what would be the best outfit for today. The current temperature is ",temperature_in_celsius ," celsius and rain is:", rain_in_mm, "mm. Give size in inches if any. Don't assume customer size if they don't share it. Give ideas of colors and other items to match. The user added this instruction based on what they like: ", requested_style)
# MAGIC   ) AS recommended_outfit;
# MAGIC
# MAGIC -- let's test our function:
# MAGIC SELECT recommend_outfit_description("I need a dress for an interview.", 30.1, 0.0)

# COMMAND ----------

# MAGIC %md-sandbox
# MAGIC ### Using Vector search to find similar content as a tool
# MAGIC
# MAGIC Let's now add a tool to recomment similar items, based on an article description.
# MAGIC
# MAGIC We'll be using Databricks Vector Search to perform a realtime similarity search and return articles that we could suggest from our database.
# MAGIC
# MAGIC Do do so, you can leverage the new `vector_search` SQL function. See [Documentation](https://docs.databricks.com/en/sql/language-manual/functions/vector_search.html) for more details.
# MAGIC
# MAGIC <div style="background-color: #e3efff"> To simplify this demo, we'll fake the call to the vector_search and make it work without pre-loading the demo</div>

# COMMAND ----------

# MAGIC %sql
# MAGIC -- Commenting this as the index isn't pre-loaded in the demo to simplify the experience.
# MAGIC -- CREATE OR REPLACE FUNCTION find_clothes_matching_description (description STRING)
# MAGIC -- RETURNS TABLE (category STRING, color STRING, id STRING, price DOUBLE, search_score DOUBLE)
# MAGIC -- LANGUAGE SQL
# MAGIC -- COMMENT 'Finds clothes in our catalog matching the description using AI query and returns a table of results.'
# MAGIC -- RETURN
# MAGIC --  SELECT * FROM VECTOR_SEARCH(index => 'catalog.schema.clothing_index', query => query, num_results => 3) vs
# MAGIC

# COMMAND ----------

# MAGIC %sql
# MAGIC -- Generate fake data instead of calling the VS index with vector_search;
# MAGIC CREATE OR REPLACE FUNCTION find_clothes_matching_description (description STRING)
# MAGIC RETURNS TABLE (id BIGINT, name STRING, color STRING, category STRING, price DOUBLE, description STRING)
# MAGIC COMMENT 'Finds existing clothes in our catalog matching the description using AI query and returns a table of results.'
# MAGIC RETURN
# MAGIC SELECT clothes.* FROM (
# MAGIC   SELECT explode(from_json(
# MAGIC     ai_query(
# MAGIC       'databricks-meta-llama-3-70b-instruct', 
# MAGIC       CONCAT(
# MAGIC         'returns a json list of 3 json object clothes: <"id": bigint, "name": string, "color": string, "category": string, "price": double, "description": string>. These clothes should match the following user description: ', description, '. Return only the answer as a javascript json object ready to be parsed, no comment or text or javascript or ``` at the beginning.' ) ), 'ARRAY<STRUCT<id: BIGINT, name: STRING, color: STRING, category: STRING, price: DOUBLE, description: STRING>>' )) AS clothes );
# MAGIC
# MAGIC -- let's test our function:
# MAGIC SELECT * FROM find_clothes_matching_description('a red dress');

# COMMAND ----------

# MAGIC %md-sandbox
# MAGIC ## Using Databricks Playground to test our functions
# MAGIC
# MAGIC Databricks Playground provides a built-in integration with your functions. It'll analyze which functions are available, and call them to properly answer your question.
# MAGIC
# MAGIC
# MAGIC <img src="https://github.com/databricks-demos/dbdemos-resources/blob/main/images/product/llm-tools-functions/llm-tools-functions-playground.gif?raw=true" style="float: right; margin-left: 10px; margin-bottom: 10px;">
# MAGIC
# MAGIC To try out our functions with playground:
# MAGIC - Open the Playground 
# MAGIC - Select a model supporting tools (like Llama3.1)
# MAGIC - Add the functions you want your model to leverage (`catalog.schema.function_name`)
# MAGIC - Ask a question (for example to convert inch to cm), and playground will do the magic for you!
# MAGIC
# MAGIC <br/>
# MAGIC <div style="background-color: #d4e7ff; padding: 10px; border-radius: 15px;clear:both">
# MAGIC <strong>Note:</strong> Tools in playground is in preview, reach-out your Databricks Account team for more details and to enable it.
# MAGIC </div>
# MAGIC

# COMMAND ----------

# MAGIC %md
# MAGIC
# MAGIC ## Building an AI system leveraging our Databricks UC functions with Langchain
# MAGIC
# MAGIC These tools can also directly be leveraged on custom model. In this case, you'll be in charge of chaining and calling the functions yourself (the playground does it for you!)
# MAGIC
# MAGIC Langchain makes it easy for you. You can create your own custom AI System using a Langchain model and a list of existing tools (in our case, the tools will be the functions we just created)

# COMMAND ----------

# MAGIC %md
# MAGIC ### Enable MLflow Tracing
# MAGIC
# MAGIC Enabling MLflow Tracing is required to:
# MAGIC - View the chain's trace visualization in this notebook
# MAGIC - Capture the chain's trace in production via Inference Tables
# MAGIC - Evaluate the chain via the Mosaic AI Evaluation Suite

# COMMAND ----------

import mlflow
mlflow.langchain.autolog(disable=False)

# COMMAND ----------

# MAGIC %md
# MAGIC ### Start by creating our tools from Unity Catalog
# MAGIC
# MAGIC Let's use UCFunctionToolkit to select which functions we want to use as tool for our demo:

# COMMAND ----------

from langchain_community.tools.databricks import UCFunctionToolkit
import pandas as pd
wh = get_shared_warehouse(name = None) #Get the first shared wh we can. See _resources/01-init for details
print(f'This demo will be using the wg {wh.name} to execute the functions')

def get_tools():
    return (
        UCFunctionToolkit(warehouse_id=wh.id)
        # Include functions as tools using their qualified names.
        # You can use "{catalog_name}.{schema_name}.*" to get all functions in a schema.
        .include(f"{catalog}.{db}.*")
        .get_tools())

display_tools(get_tools()) #display in a table the tools - see _resource/00-init for details

# COMMAND ----------

# MAGIC %md 
# MAGIC ### Let's create our langchain agent using the tools we just created

# COMMAND ----------

# DBTITLE 1,Create the chat

from langchain_openai import ChatOpenAI
hostname = dbutils.notebook.entry_point.getDbutils().notebook().getContext().browserHostName().get()
# Note: langchain_community.chat_models.ChatDatabricks doesn't support create_tool_calling_agent yet
# Let's use ChatOpenAI for now
llm = ChatOpenAI(
  base_url=f"https://{hostname}/serving-endpoints/",
  api_key=dbutils.notebook.entry_point.getDbutils().notebook().getContext().apiToken().get(),
  model="databricks-meta-llama-3-70b-instruct"
)


# COMMAND ----------

# DBTITLE 1,Define the Prompt
from langchain_core.prompts import ChatPromptTemplate
from langchain_community.chat_models import ChatDatabricks

def get_prompt(history = [], prompt = None):
    if not prompt:
            prompt = """You are a helpful fashion assistant. Your task is to recommend cothes to the users. You can use the following tools:
    - Use the convert_inch_to_cm to covert inch to cm if the customer ask for it
    - Use get_customer_orders to get the list of orders and their status, total amount and number of article. 
    - Use find_clothes_matching_description to find existing clothes from our internal catalog and suggest article to the customer
    - Use recommend_outfit if a customer ask you for a style. This function take the weather as parameter. Use the get_weather function first before calling this function to get the current temperature and rain. The current user location is 52.52, 13.41.

    Make sure to use the appropriate tool for each step and provide a coherent response to the user. Don't mention tools to your users. Only answer what the user is asking for. If the question isn't related to the tools or style/clothe, say you're sorry but can't answer"""
    return ChatPromptTemplate.from_messages([
            ("system", prompt),
            ("human", "{input}"),
            ("placeholder", "{agent_scratchpad}"),
    ])

# COMMAND ----------

from langchain.agents import AgentExecutor, create_tool_calling_agent
prompt = get_prompt()
tools = get_tools()
agent = create_tool_calling_agent(llm, tools, prompt)
agent_executor = AgentExecutor(agent=agent, tools=tools, verbose=True)

# COMMAND ----------

# MAGIC %md 
# MAGIC ### Let's give it a try: Asking to run a simple size conversion.
# MAGIC Under the hood, we want this to call our Math conversion function:

# COMMAND ----------

agent_executor.invoke({"input": "what's 12in in cm?"})

# COMMAND ----------

agent_executor.invoke({"input": "what's are my latest orders?"})

# COMMAND ----------

# MAGIC %md 
# MAGIC ### Chaining multiple tools
# MAGIC
# MAGIC Let's see if the agent can properly chain the calls, using multiple tools and passing the values from one to another. We'll ask for an outfit for today, and the expectation is that the LLM will fetch the weather before.

# COMMAND ----------

agent_executor = AgentExecutor(agent=agent, tools=tools, verbose=True)
answer = agent_executor.invoke({"input": "I need a dress for an Interview I have today. What style would recommend for today?"})

# COMMAND ----------

#Note: in a real app, we would include the preview discussion as history to keep the reference.
answer = agent_executor.invoke({"input": "Can you give me a list of red dress I can buy?"})

# COMMAND ----------

displayHTML(answer['output'].replace('\n', '<br>'))

# COMMAND ----------

# MAGIC %md
# MAGIC ## Extra: running more advanced functions using python:
# MAGIC
# MAGIC Let's see a few more advanced tools example

# COMMAND ----------

# MAGIC %md 
# MAGIC ### Calculator tool: Supporting math operations 
# MAGIC Let's add a function to allow our llm to execute any Math operation. 
# MAGIC
# MAGIC Databricks runs the python in a safe container. However, we'll filter what the function can do to avoid any potential issues with prompt injection (so that the user cannot execute other python instructions).

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE OR REPLACE FUNCTION compute_math(expr STRING)
# MAGIC RETURNS STRING
# MAGIC LANGUAGE PYTHON
# MAGIC COMMENT 'Run any mathematical function and returns the result as output. Supports python syntax like math.sqrt(13)'
# MAGIC AS
# MAGIC $$
# MAGIC   import ast
# MAGIC   import operator
# MAGIC   import math
# MAGIC   operators = {ast.Add: operator.add, ast.Sub: operator.sub, ast.Mult: operator.mul, ast.Div: operator.truediv, ast.Pow: operator.pow, ast.Mod: operator.mod, ast.FloorDiv: operator.floordiv, ast.UAdd: operator.pos, ast.USub: operator.neg}
# MAGIC     
# MAGIC   # Supported functions from the math module
# MAGIC   functions = {name: getattr(math, name) for name in dir(math) if callable(getattr(math, name))}
# MAGIC
# MAGIC   def eval_node(node):
# MAGIC     if isinstance(node, ast.Num):  # <number>
# MAGIC       return node.n
# MAGIC     elif isinstance(node, ast.BinOp):  # <left> <operator> <right>
# MAGIC       return operators[type(node.op)](eval_node(node.left), eval_node(node.right))
# MAGIC     elif isinstance(node, ast.UnaryOp):  # <operator> <operand> e.g., -1
# MAGIC       return operators[type(node.op)](eval_node(node.operand))
# MAGIC     elif isinstance(node, ast.Call):  # <func>(<args>)
# MAGIC       func = node.func.id
# MAGIC       if func in functions:
# MAGIC         args = [eval_node(arg) for arg in node.args]
# MAGIC         return functions[func](*args)
# MAGIC       else:
# MAGIC         raise TypeError(f"Unsupported function: {func}")
# MAGIC     else:
# MAGIC       raise TypeError(f"Unsupported type: {type(node)}")  
# MAGIC   try:
# MAGIC     if expr.startswith('```') and expr.endswith('```'):
# MAGIC       expr = expr[3:-3].strip()      
# MAGIC     node = ast.parse(expr, mode='eval').body
# MAGIC     return eval_node(node)
# MAGIC   except Exception as ex:
# MAGIC     return str(ex)
# MAGIC $$;
# MAGIC -- let's test our function:
# MAGIC SELECT compute_math("(2+2)/3") as result;

# COMMAND ----------

# MAGIC %md
# MAGIC ### Run any python function
# MAGIC
# MAGIC If we are creating an coding assistant, it can be useful to allow our AI System to run python code to try them, and output the results to the user. **Be careful doing that, as any code could be executed by the user.**
# MAGIC
# MAGIC Here is an example:

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE OR REPLACE FUNCTION execute_python_code(python_code STRING)
# MAGIC RETURNS STRING
# MAGIC LANGUAGE PYTHON
# MAGIC COMMENT 'Run any python code and returns the output'
# MAGIC AS
# MAGIC $$
# MAGIC   import traceback
# MAGIC   try:
# MAGIC       if python_code.startswith('```') and python_code.endswith('```'):
# MAGIC           python_code = python_code[3:-3].strip()      
# MAGIC       result = eval(python_code, globals())
# MAGIC       return str(result)
# MAGIC   except Exception as ex:
# MAGIC       return traceback.format_exc()
# MAGIC $$;
# MAGIC -- let's test our function:
# MAGIC
# MAGIC SELECT execute_python_code("'Hello Word! '* 3") as result;

# COMMAND ----------

from langchain.agents import AgentExecutor, create_tool_calling_agent
prompt = get_prompt(prompt="You are an assistant for python developer. you can run any python code the customer is asking for to output to test and run the code, and display the output. Don't mention you have tools or the tools name. Make sure you send the full python code to the function")
tools = get_tools()
agent = create_tool_calling_agent(llm, tools, prompt)
agent_executor = AgentExecutor(agent=agent, tools=tools, verbose=True)
answer = agent_executor.invoke({"input": "Write me a function that compute fibonacci suite in python, and display its result for 5."})
displayHTML(answer['output'].replace('\n', '<br>'))

# COMMAND ----------

# MAGIC %md
# MAGIC ## Conclusion
# MAGIC That's it, we saw how you can leverage Databricks Functions as tools within your AI system.
# MAGIC
# MAGIC This demo gave you a simple overview and some example to get started. You can take it to the next level within your own AI Systems!
# MAGIC
# MAGIC Once your application complete and your chain ready to be deployed, you can easily serve your model as a Model Serving Endpoint, acting as your Compound AI System!
# MAGIC
# MAGIC ### Coming soon
# MAGIC
# MAGIC We'll soon update this demo to add more example, including:
# MAGIC - how to properly leverage secrets within AI functions to call external system having Authentication
# MAGIC - generating images and calling ML models endpoints
# MAGIC - Use Genie as an agent to query any table!
# MAGIC - More to come!
# MAGIC
# MAGIC Stay tuned!

# COMMAND ----------

# MAGIC %pip install mlflow databricks-agents
# MAGIC dbutils.library.restartPython()
# MAGIC
# MAGIC import mlflow
# MAGIC import pandas as pd
# MAGIC
# MAGIC examples =  {
# MAGIC     "request": [
# MAGIC         "What is Spark?",
# MAGIC         "How do I convert a Spark DataFrame to Pandas?",
# MAGIC     ],
# MAGIC     "response": [
# MAGIC         "Spark is a data analytics framework.",
# MAGIC         "This is not possible as Spark is not a panda.",
# MAGIC     ],
# MAGIC     "retrieved_context": [ # Optional, needed for judging groundedness.
# MAGIC         [{"doc_uri": "doc1.txt", "content": "In 2013, Spark, a data analytics framework, was open sourced by UC Berkeley's AMPLab."}],
# MAGIC         [{"doc_uri": "doc2.txt", "content": "To convert a Spark DataFrame to Pandas, you can use toPandas()"}],
# MAGIC     ],
# MAGIC     "expected_response": [ # Optional, needed for judging correctness.
# MAGIC         "Spark is a data analytics framework.",
# MAGIC         "To convert a Spark DataFrame to Pandas, you can use the toPandas() method.",
# MAGIC     ]
# MAGIC }
# MAGIC
# MAGIC result = mlflow.evaluate(
# MAGIC     data=pd.DataFrame(examples),    # Your evaluation set
# MAGIC     predictions="response",         # Specify the column containing model outputs
# MAGIC     model_type="databricks-agent",  # Enable Mosaic AI Agent Evaluation
# MAGIC )
# MAGIC
# MAGIC # Review the evaluation results in the MLFLow UI (see console output), or access them in place:
# MAGIC display(result.tables['eval_results'])

# COMMAND ----------

# MAGIC %sql
# MAGIC DECLARE count INT;
# MAGIC SET count = 1;
# MAGIC
# MAGIC DECLARE Sum INT;
# MAGIC SET Sum = 0;
# MAGIC
# MAGIC BEGIN
# MAGIC     WHILE count <= 10 DO
# MAGIC         INSERT INTO tab_script VALUES (count); 
# MAGIC   SET Sum = Sum + count;
# MAGIC         SET count = count + 1;
# MAGIC     END WHILE;
# MAGIC END;
# MAGIC
# MAGIC SELECT Sum AS sum_of_numbers;
# MAGIC